//Creado con Ardora - www.webardora.net
//bajo licencia Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
//para otros usos contacte con el autor
var timeAct=360; timeIni=360; timeBon=0;
var successes=0; successesMax=3; attempts=0; attemptsMax=1;
var score=0; scoreMax=15; scoreInc=5; scoreDec=5
var typeGame=0;
var tiTime=true;
var tiTimeType=0;
var tiButtonTime=true;
var textButtonTime="Comenzar";
var tiSuccesses=true;
var tiAttempts=true;
var tiScore=true;
var startTime;
var colorBack="#FFFDFD"; colorButton="#91962F"; colorText="#000000"; colorSele="#FF8000";
var goURLNext=false; goURLRepeat=false;tiAval=false;
var scoOk=0; scoWrong=0; scoOkDo=0; scoWrongDo=0; scoMessage=""; scoPtos=10;
var fMenssage="Verdana, Geneva, sans-serif";
var fActi="Verdana, Geneva, sans-serif";
var fEnun="Verdana, Geneva, sans-serif";
var timeOnMessage=5; messageOk="¡Excelente! Lograste reconstruir la secuencia lógica"; messageTime="10 minutos"; messageError="Incorrecto: Revisa la relación temporal entre los eventos y la conexión de causa-consecuencia."; messageErrorG="Incorrecto: Revisa la relación temporal entre los eventos y la conexión de causa-consecuencia."; messageAttempts="2"; isShowMessage=false;
var urlOk=""; urlTime=""; urlError=""; urlAttempts="";
var goURLOk="_blank"; goURLTime="_blank"; goURLAttempts="_blank"; goURLError="_blank"; 
borderOk="#008000"; borderTime="#FF0000";borderError="#FF0000"; borderAttempts="#FF0000";
var wordsGame="c2VjdWVuY2lhbF9pbmRleA=="; wordsStr = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function giveZindex(typeElement){var valueZindex=0; capas=document.getElementsByTagName(typeElement);
for (i=0;i<capas.length;i++){if (parseInt($(capas[i]).css("z-index"),10)>valueZindex){valueZindex=parseInt($(capas[i]).css("z-index"),10);}}return valueZindex;}
var actMaxWidth="600"; actMaxHeight="400";profG=0;dirMedia="secuencial_index_resources/media/";
var indexG=0;
var words1G=["Q2FkYSB0YXJkZSwgQ2FybGEgcGFzYWJhIHBvciBlbCBwYXJxdWUgZGUgc3UgYmFycmlvIGNhbWlubyBhIGNhc2EsIHkgc2llbXByZSBub3RhYmEgdW4gZmFyb2wgYXBhZ2FkbyBjZXJjYSBkZWwgbGFnby4=","VW5hIG5vY2hlLCBkZWNpZGnDsyBhY2VyY2Fyc2UgeSBkZXNjdWJyacOzIHF1ZSBlbCBmYXJvbCBlc3RhYmEgZW5jZW5kaWRvLCBhdW5xdWUgbm8gaGFiw61hIG5hZGllIGFscmVkZWRvciB5IGVsIHBhcnF1ZSBlc3RhYmEgZGVzaWVydG8u","QWwgbWlyYXIgbcOhcyBkZSBjZXJjYSwgdmlvIHF1ZSBkZW50cm8gZGVsIGZhcm9sIGhhYsOtYSB1bmEgcGVxdWXDsWEgbm90YSBlbnJvbGxhZGEgcXVlIGRlY8OtYTog4oCcU2lndWUgbGEgbHV6IHkgaGFsbGFyw6FzIGxvIHF1ZSBidXNjYXPigJ0u","R3VpYWRhIHBvciBsYSBsdXosIGNhbWluw7MgaGFjaWEgdW4gc2VuZGVybyBvY3VsdG8gZW50cmUgbG9zIMOhcmJvbGVzIHF1ZSBudW5jYSBhbnRlcyBoYWLDrWEgdmlzdG8u","QWwgZmluYWwgZGVsIHNlbmRlcm8sIGVuY29udHLDsyB1biBwZXF1ZcOxbyBiYW5jbyBjb24gdW4gbGlicm8gYW50aWd1byBlbmNpbWEsIGN1YmllcnRvIGRlIHBvbHZvLCBxdWUgcGFyZWPDrWEgZXNwZXJhciBhIHF1ZSBhbGd1aWVuIGxvIGRlc2N1YnJpZXJhLg==","QWJyacOzIGVsIGxpYnJvIHkgdmlvIHF1ZSBlc3RhYmEgbGxlbm8gZGUgaGlzdG9yaWFzIGVzY3JpdGFzIHBvciBsb3MgaGFiaXRhbnRlcyBkZWwgYmFycmlvLCBkZXNkZSBoYWNlIGTDqWNhZGFzLCBjb21vIHVuIHJlZ2lzdHJvIHNlY3JldG8gZGUgbGEgY29tdW5pZGFkLg==","Q2FybGEgY29tcHJlbmRpw7MgcXVlIGVsIGZhcm9sIHkgZWwgbGlicm8gZXJhbiBwYXJ0ZSBkZSB1biBsZWdhZG8gcXVlIGNvbmVjdGFiYSBhIGxhcyBnZW5lcmFjaW9uZXMgZGVsIGJhcnJpbywgeSBkZWNpZGnDsyBjb25zZXJ2YXIgZWwgc2VjcmV0byBwYXJhIGNvbXBhcnRpcmxvIGFsZ8O6biBkw61hIGNvbiBvdHJvcyBuacOxb3MgY3VyaW9zb3Mu","RGVzZGUgYXF1ZWxsYSBub2NoZSwgY2FkYSB2ZXogcXVlIHBhc2FiYSBwb3IgZWwgcGFycXVlLCBzYWx1ZGFiYSBhbCBmYXJvbCwgY29tbyBzaSBmdWVyYSB1biBhbWlnbyBzaWxlbmNpb3NvIHF1ZSBndWFyZGFiYSBoaXN0b3JpYXMgeSBzZWNyZXRvcyBwYXJhIHF1aWVuZXMgc2UgYXRyZXbDrWFuIGEgYnVzY2FyLg=="];
var words2G=["RGFuaWVsIG9ic2VydmFiYSBlbCB2aWVqbyByZWxvaiBkZSBww6luZHVsbyBxdWUgY29sZ2FiYSBlbiBsYSBzYWxhIGRlIHN1IGFidWVsby4gTmFkaWUgc2Fiw61hIGV4YWN0YW1lbnRlIGRlc2RlIGN1w6FuZG8gZXN0YWJhIGFsbMOtLCBwZXJvIHRvZG9zIGRlY8OtYW4gcXVlIG51bmNhIHNlIGhhYsOtYSBkZXRlbmlkby4=","VW4gZMOtYSwgYWwgbGxlZ2FyIGRlIGxhIGVzY3VlbGEsIERhbmllbCBub3TDsyBxdWUgZWwgcmVsb2ogaGFiw61hIGRlamFkbyBkZSBtYXJjYXIgbGEgaG9yYS4gRWwgdGljLXRhYyBjb25zdGFudGUgaGFiw61hIGRlc2FwYXJlY2lkbywgeSBsYSBjYXNhIHNlIHNlbnTDrWEgZXh0cmHDsWFtZW50ZSBzaWxlbmNpb3NhLg==","SW50cmlnYWRvLCBzZSBhY2VyY8OzIGFsIHJlbG9qIHkgZGVzY3VicmnDsyB1bmEgcGVxdWXDsWEgbGxhdmUgb3hpZGFkYSBlbiBlbCBzdWVsbywganVzdG8gZGViYWpvIGRlbCBww6luZHVsbyBpbm3Ds3ZpbC4=","U2luIHBlbnNhcmxvIGRlbWFzaWFkbywgRGFuaWVsIHRvbcOzIGxhIGxsYXZlIHkgbGEgaW50cm9kdWpvIGVuIHVuYSByYW51cmEgY2FzaSBpbnZpc2libGUgZW4gbGEgcGFydGUgdHJhc2VyYSBkZWwgcmVsb2ouIEFsIGdpcmFybGEsIGVzY3VjaMOzIHVuIGxldmUgY2xpYyB5IGVsIHDDqW5kdWxvIGNvbWVuesOzIGEgbW92ZXJzZSBsZW50YW1lbnRlLg==","RW4gZXNlIG1vbWVudG8sIHVuYSBjb3JyaWVudGUgZGUgYWlyZSBmcsOtbyByZWNvcnJpw7MgbGEgc2FsYSB5IGVsIHRpZW1wbyBwYXJlY2nDsyBkZXRlbmVyc2UgcG9yIGNvbXBsZXRvLiBEYW5pZWwgbWlyw7MgYSBzdSBhbHJlZGVkb3I6IGxvcyBjdWFkcm9zLCBsYXMgY29ydGluYXMgeSBoYXN0YSBlbCBwb2x2byBxdWVkYXJvbiBzdXNwZW5kaWRvcyBlbiBlbCBhaXJlLg==","RGUgcHJvbnRvLCB1bmEgZmlndXJhIGx1bWlub3NhIGFwYXJlY2nDsyByZWZsZWphZGEgZW4gZWwgY3Jpc3RhbCBkZWwgcmVsb2ouIEVyYSBzdSBhYnVlbG8sIHF1ZSBoYWLDrWEgZmFsbGVjaWRvIGVsIGHDsW8gYW50ZXJpb3IsIHkgbGUgc29ucmXDrWEgY29uIHRlcm51cmEu","RWwgYWJ1ZWxvIGxlIGhhYmzDsyBjb24gdm96IHNlcmVuYSwgZGljacOpbmRvbGUgcXVlIGVsIHJlbG9qIGd1YXJkYWJhIGxvcyByZWN1ZXJkb3MgZGUgbGEgZmFtaWxpYSwgeSBxdWUgY2FkYSBnZW5lcmFjacOzbiBkZWLDrWEgaGFjZXJsbyBmdW5jaW9uYXIgcGFyYSBtYW50ZW5lciB2aXZhIHN1IGhpc3RvcmlhLg==","Q3VhbmRvIERhbmllbCBkZXNwZXJ0w7MsIGVsIHJlbG9qIHNlZ3XDrWEgbWFyY2FuZG8gbGEgaG9yYSBjb24gcHJlY2lzacOzbi4gTm8gc2Fiw61hIHNpIGxvIHF1ZSBoYWLDrWEgdml2aWRvIGZ1ZSB1biBzdWXDsW8sIHBlcm8gZGVzZGUgZW50b25jZXMgc2UgYXNlZ3Vyw7MgZGUgZGFybGUgY3VlcmRhIGNhZGEgbm9jaGUu"];
var words3G=["SGFiw61hIHVuYSB2ZXogdW4gbmnDsW8gbGxhbWFkbyBUb23DoXMgcXVlIGFkb3JhYmEgbWlyYXIgbGFzIGVzdHJlbGxhcyBkZXNkZSBzdSB2ZW50YW5hLg==","VW5hIG5vY2hlLCB2aW8gdW5hIGx1eiBicmlsbGFudGUgcXVlIGNhecOzIGVuIGVsIGJvc3F1ZSBkZXRyw6FzIGRlIHN1IGNhc2Eu","VG9tw6FzIGRlY2lkacOzIHNhbGlyIGVuIHNpbGVuY2lvIHkgZnVlIGhhc3RhIGVsIGJvc3F1ZSBwYXJhIGRlc2N1YnJpciBxdcOpIGVyYS4=","QWxsw60gZW5jb250csOzIHVuYSBwZXF1ZcOxYSBwaWVkcmEgcXVlIGJyaWxsYWJhIGNvbiBjb2xvcmVzIGRlbCBhcmNvw61yaXMu","Q3VhbmRvIGxhIHRvY8OzLCBsYSBwaWVkcmEgZW1wZXrDsyBhIGZsb3RhciB5IG1vc3Ryw7MgdW4gbWFwYSBlbiBlbCBhaXJlLg==","VG9tw6FzIHNpZ3Vpw7MgZWwgbWFwYSB5IGxsZWfDsyBhIHVuIGNsYXJvIGRvbmRlIHVuYSBlc3RyZWxsYSBkaW1pbnV0YSBsbyBlc3BlcmFiYQ==","TGEgZXN0cmVsbGEgbGUgYWdyYWRlY2nDsyBwb3IgYXl1ZGFybGEgYSB2b2x2ZXIgYWwgY2llbG8u","RGVzZGUgZW50b25jZXMsIGNhZGEgbm9jaGUgVG9tw6FzIG1pcmEgYWwgY2llbG8gc2FiaWVuZG8gcXVlIHRpZW5lIHVuYSBhbWlnYSBlbnRyZSBsYXMgZXN0cmVsbGFzLg=="];
var c1=[116,132,132,96,145,152,193,177];
var c2=[176,175,114,195,207,152,174,176];
var c3=[85,73,77,71,70,79,56,96];
